# Generated by Django 6.1.1 on 2026-09-23 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scores', to='detection.event'),
        ),
        migrations.AlterField(
            model_name='score',
            name='tier',
            field=models.CharField(blank=True, choices=[('allow', 'Allow'), ('otp', 'OTP Challenge'), ('block', 'Block')], max_length=10, null=True),
        ),
    ]
