# Generated by Django 6.1.1 on 2026-09-23 19:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detection', '0002_score_event_alter_score_tier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('otp_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_verified', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_challenges', to='detection.session')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='otp_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id_raw', models.CharField(blank=True, default='', max_length=100)),
                ('username_attempted', models.CharField(blank=True, default='anonymous', max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('risk_score', models.FloatField(help_text='Authoritative server risk score: 0.0 (Human) to 1.0 (Bot)')),
                ('action_taken', models.CharField(choices=[('ALLOW', 'Allow'), ('OTP', 'OTP Required'), ('BLOCK', 'Block Access')], max_length=10)),
                ('reason', models.TextField(default='Standard behavioral evaluation')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_logs', to='detection.session')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
