# Generated by Django 6.1.1 on 2026-09-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpchallenge',
            name='otp_hash',
            field=models.CharField(max_length=256),
        ),
    ]
